name: Build and Push Backend Users

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t backend-users:v1 .
